### ISSUE TITLE
popt.h error

### ISSUE THREAD

**Issue by BarTtTraB** [revk/PuzzleBox#1]
When compiling, there is a popt.h error (Windows)

**Comment by revk** [comment]
Well, it would help to know what the error is! I don't have windows...

**Comment by BarTtTraB** [comment]
6 | fatal error: popt.h: No such file or directory|

**Comment by revk** [comment]
OK, well, that kinds of explains it - you don't have popt.h. You need popt for this. Install it and try again.

**Comment by BarTtTraB** [comment]
I can not find popt under windows.

**Comment by revk** [comment]
Oh, OK.

**Comment by revk** [comment]
I googled "popt for windows" and found this http://gnuwin32.sourceforge.net/packages/popt.htm
Does that help?

**Comment by BarTtTraB** [comment]
hmm.
puzzlebox.c: In function 'main':
puzzlebox.c:126:7: warning: implicit declaration of function 'errx' [-Wimplicit-function-declaration]
       errx (1, "%s: %s\n", poptBadOption (optCon, POPT_BADOPTION_NOALIAS), poptStrerror (c));
       ^~~~
puzzlebox.c:139:14: warning: implicit declaration of function 'strdupa' [-Wimplicit-function-declaration]
       path = strdupa (path);
              ^~~~~~~
puzzlebox.c:139:12: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
       path = strdupa (path);
            ^
puzzlebox.c:149:8: warning: implicit declaration of function 'asprintf' [-Wimplicit-function-declaration]
        asprintf (&error, "Path error [%s]\n", path);
        ^~~~~~~~
puzzlebox.c:379:13: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
   char *p = strdupa (*(char * *) optionsTable[o].arg), *q;
             ^~~~~~~
puzzlebox.c:397:5: warning: implicit declaration of function 'gmtime_r' [-Wimplicit-function-declaration]
     gmtime_r (&now, &t);
     ^~~~~~~~
puzzlebox.c: In function 'box':
puzzlebox.c:481:30: error: 'M_PIl' undeclared (first use in this function)
     int W = ((int) (r1 * 2 * M_PIl / mazestep)) / nubs * nubs; // Default value
                              ^~~~~
puzzlebox.c:481:30: note: each undeclared identifier is reported only once for each function it appears in
puzzlebox.c: In function 'makemaze':
puzzlebox.c:575:4: warning: implicit declaration of function 'err' [-Wimplicit-function-declaration]
    err (1, "Open /dev/random");
    ^~~
puzzlebox.c: In function 'box':
puzzlebox.c:1116:12: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
  char *p = strdupa (textend);
            ^~~~~~~
puzzlebox.c:1135:12: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
  char *p = strdupa (textsides);
            ^~~~~~~

**Comment by revk** [comment]
Well, if you don't have the gcc extensions, you could use strdup() not strdupa(). For the others, you'll need the appropriate libraries for errx(), gmtime_r(), maths, etc. I am sure it would not be too hard to make a version that will compile on windows. Good luck.

**Comment by BarTtTraB** [comment]
What does it need to compile it on Ubuntu?

**Comment by revk** [comment]
Possible popt if you don't have it, but everything else should just work.

**Comment by BarTtTraB** [comment]
On Ubuntu 18.04.1 LTS
puzzlebox.c: In function ‘main’:
puzzlebox.c:139:14: warning: implicit declaration of function ‘strdupa’; did you mean ‘strdup’? [-Wimplicit-function-declaration]
       path = strdupa (path);
              ^~~~~~~
              strdup
puzzlebox.c:139:12: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
       path = strdupa (path);
            ^
puzzlebox.c:149:8: warning: implicit declaration of function ‘asprintf’; did you mean ‘vsprintf’? [-Wimplicit-function-declaration]
        asprintf (&error, "Path error [%s]\n", path);
        ^~~~~~~~
        vsprintf
puzzlebox.c:286:14: warning: too many arguments for format [-Wformat-extra-args]
      printf ("</td>", optionsTable[o].argDescrip);
              ^~~~~~~
puzzlebox.c:379:13: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
   char *p = strdupa (*(char * *) optionsTable[o].arg), *q;
             ^~~~~~~
puzzlebox.c: In function ‘box’:
puzzlebox.c:481:30: error: ‘M_PIl’ undeclared (first use in this function); did you mean ‘M_PI’?
     int W = ((int) (r1 * 2 * M_PIl / mazestep)) / nubs * nubs; // Default value
                              ^~~~~
                              M_PI
puzzlebox.c:481:30: note: each undeclared identifier is reported only once for each function it appears in
puzzlebox.c: In function ‘addpoint’:
puzzlebox.c:806:15: warning: too many arguments for format [-Wformat-extra-args]
      errx (1, "WTF points 5d", S);
               ^~~~~~~~~~~~~~~
puzzlebox.c: In function ‘box’:
puzzlebox.c:1116:12: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
  char *p = strdupa (textend);
            ^~~~~~~
puzzlebox.c:1135:12: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
  char *p = strdupa (textsides);
            ^~~~~~~

**Comment by revk** [comment]
That seems surprising as the Makefile does define _GNU_SOURCE which should enable GNU extensions for asprintf and strdupa.

I've changed M_PIl to M_PI anyway and fixed two of the typos you spotted.

**Comment by BarTtTraB** [comment]
/tmp/ccgJN2Sm.o: In function `main':
puzzlebox.c:(.text+0xee6): undefined reference to `poptHelpOptions'
puzzlebox.c:(.text+0xf21): undefined reference to `poptGetContext'
puzzlebox.c:(.text+0xf37): undefined reference to `poptGetNextOpt'
puzzlebox.c:(.text+0xf53): undefined reference to `poptStrerror'
puzzlebox.c:(.text+0xf6a): undefined reference to `poptBadOption'
puzzlebox.c:(.text+0xf95): undefined reference to `poptPeekArg'
puzzlebox.c:(.text+0xfb8): undefined reference to `poptPrintUsage'
puzzlebox.c:(.text+0xfd1): undefined reference to `poptFreeContext'
puzzlebox.c:(.text+0x1000): undefined reference to `strdupa'
puzzlebox.c:(.text+0x254d): undefined reference to `strdupa'
/tmp/ccgJN2Sm.o: In function `makemaze.5307':
puzzlebox.c:(.text+0x31d3): undefined reference to `atan'
puzzlebox.c:(.text+0x46db): undefined reference to `sin'
puzzlebox.c:(.text+0x4702): undefined reference to `cos'
/tmp/ccgJN2Sm.o: In function `box.5287':
puzzlebox.c:(.text+0x6726): undefined reference to `cos'
puzzlebox.c:(.text+0x6d63): undefined reference to `cos'
puzzlebox.c:(.text+0x6e09): undefined reference to `cos'
puzzlebox.c:(.text+0x716c): undefined reference to `strdupa'
puzzlebox.c:(.text+0x72e2): undefined reference to `sin'
puzzlebox.c:(.text+0x7309): undefined reference to `strdupa'
/tmp/ccgJN2Sm.o: In function `addnub.5555':
puzzlebox.c:(.text+0x8590): undefined reference to `cos'
puzzlebox.c:(.text+0x85e9): undefined reference to `sin'
puzzlebox.c:(.text+0x86f8): undefined reference to `cos'
puzzlebox.c:(.text+0x871f): undefined reference to `sin'
collect2: error: ld returned 1 exit status

**Comment by BarTtTraB** [comment]
on terminal, 
/PuzzleBox-master$ make puzzlebox

**Comment by revk** [comment]
Well, the cc line includes -lm (for maths) and -lpopt (for popt) so those functions should all be linked in. Maybe google a bit more...

**Comment by BarTtTraB** [comment]
I restarted the laptop and now there is something like that:

indent puzzlebox.c
make: indent: Command not found
Makefile:2: recipe for target 'puzzlebox' failed
make: [puzzlebox] Error 127 (zignorowano)
cc -O -o puzzlebox puzzlebox.c -lpopt -lm -g -D_GNU_SOURCE
puzzlebox.c: In function ‘main’:
puzzlebox.c:152:8: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
        asprintf (&error, "Path error [%s]\n", path);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
puzzlebox.c:160:8: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
        asprintf (&error, "Unknown arg [%c]", arg);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
puzzlebox.c:169:7: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
       asprintf (&error, "Missing value [%c=]", arg);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
puzzlebox.c:178:7: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
       asprintf (&error, "Missing value [%c=]", arg);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
puzzlebox.c:196:7: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
       asprintf (&error, "Missing value [%c=]", arg);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by revk** [comment]
Ok those are warnings you can ignore. I may change later to remove those.

**Comment by BarTtTraB** [comment]
ok, a puzzlebox file has been created, what's next?

**Comment by revk** [comment]
Err, run it, the output is an OpenSCAD file!
If you run with --help you see the various options available.

**Comment by BarTtTraB** [comment]
How should I run it in OpenSCAD? OpenSCAD can not see this file.

**Comment by revk** [comment]
Your run puzzlebox, and the output is an OpenSCAD file, put it somewhere, e.g.
./puzzlebox > mypuzzle.scad

**Comment by BarTtTraB** [comment]
how run puzzlebox?

**Comment by revk** [comment]
How do you normally run something?
You type the name/path of the thing.
Try something like

./puzzlebox > mypuzzle.scad

As I suggested above.

**Comment by BarTtTraB** [comment]
double click :p

**Comment by BarTtTraB** [comment]
but the file that you have created does not have the .scad format

**Comment by revk** [comment]
The output from puzzlebox is an SCAD file. In what way is it not ".scad" format?

If you normally just "double click" I am rather surprised you are trying to build this from source rather than just using the web page https://www.me.uk/puzzlebox to make an SCAD. Are you planning to make changes to the code?

**Comment by BarTtTraB** [comment]
I have ;
MakeFile
makesamples
puzzlebox <- this created
puzzlebox.c
README.md
webform.cgi

**Comment by revk** [comment]
Yes, and running it makes an SCAD file.
Did you try :-

./puzzlebox > mypuzzle.scad

**Comment by BarTtTraB** [comment]
/PuzzleBox-master/puzzlebox.scad", line 1: syntax error 
ERROR: Compilation failed!

**Comment by revk** [comment]
What on earth did you do to create that error?

**Comment by revk** [comment]
What is in line 1 of puzzlebox.scad

**Comment by revk** [comment]
What, what is puzzlebox.scad anyway, if you ran

./puzzlebox > mypuzzle.scad

You would have mypuzzle.scad

You did not rename puzzlebox to puzzlebox.scad did you?

**Comment by BarTtTraB** [comment]
I changed the name to puzzlebox.scad, I do not have this file mypuzzle.scad

**Comment by revk** [comment]
OK, I have given you a command you can run that will make mypuzzle.scad several times now and you have not run it.

At this point you have gone from simple PEBKAC to trolling.

Have a nice day.

**Comment by BarTtTraB** [comment]
I'm sorry I did not want to piss you off, linux is not the system on which I work.

**Comment by BarTtTraB** [comment]
Now I understand that I have to enter it in the terminal.
./puzzlebox> mypuzzle.scad

**Comment by BarTtTraB** [comment]
Would you help just one more thing?

**Comment by revk** [comment]
What?

**Comment by BarTtTraB** [comment]
where should I enter this --help?

**Comment by revk** [comment]
You need to go and read up on how to actually use command line!

I am surprised you have gone to the bother of building this from source and not just using https://www.me.uk/puzzlebox

However, try this (yes, it means typing it at the command line prompt!)

./puzzlebox --help

**Comment by BarTtTraB** [comment]
you're a Good Man, thx for all :)
