### ISSUE TITLE
Overhang angle too flat

### ISSUE THREAD

**Issue by ristein** [revk/PuzzleBox#15]
The first overhang angle is too flat to be printed nicely.
My printer can print anything above 40°, the angle should be increased a little:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/55446611/146515744-a73c15c9-b445-4191-892f-35ce6470b0f9.png">

edit: puzzlebox-4m-3N-3H-10b-22c-50h-1B6-0G4-1w2-2t-3z-1M--1X-0p7-0g4-7s-2r-1R333333-e-Z-1T-0y1-0Z2

**Comment by revk** [comment]
Odd, I don't remember making that different :-)

**Comment by revk** [comment]
OK, good news, the height of that is defined as mazmargin, default to 1mm, but you can change, e.g. 2mm, and it will be a better angle.
