### ISSUE TITLE
Won't build on a mac - several issues

### ISSUE THREAD

**Issue by rkarlsba** [revk/PuzzleBox#2]
Dora:PuzzleBox roy$ make
indent puzzlebox.c
Error@523: Unterminated literal
make: [puzzlebox] Error 1 (ignored)
cc -O -o puzzlebox puzzlebox.c -lpopt -lm -g -D_GNU_SOURCE
puzzlebox.c:3:2: error: expected identifier or '('
        2018 Adrian Kennard www.me.uk @ TheRealRevK
        ^
puzzlebox.c:46:2: error: expected expression
        ,should be less than clearance, can be - ve
        ^
puzzlebox.c:46:3: error: use of undeclared identifier 'should'
        ,should be less than clearance, can be - ve
         ^
puzzlebox.c:120:73: error: use of undeclared identifier 'nubzclearance'; did you mean 'nubrclearance'?
        {"nub-z-clearance", 'Z', POPT_ARG_DOUBLE | POPT_ARGFLAG_SHOW_DEFAULT, &nubzclearance, 0, "Extra clearance on height of nub", "mm"},
                                                                               ^~~~~~~~~~~~~
                                                                               nubrclearance
puzzlebox.c:44:10: note: 'nubrclearance' declared here
        double          nubrclearance = 0.1;
                        ^
puzzlebox.c:132:3: error: use of undeclared identifier 'command'
                command - line options
                ^
puzzlebox.c:132:13: error: use of undeclared identifier 'line'; did you mean 'link'?
                command - line options
                          ^~~~
                          link
/usr/include/unistd.h:463:6: note: 'link' declared here
int      link(const char *, const char *);
         ^
puzzlebox.c:151:10: warning: implicit declaration of function 'strdupa' is invalid in C99 [-Wimplicit-function-declaration]
                path = strdupa(path);
                       ^
puzzlebox.c:151:8: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
                path = strdupa(path);
                     ^ ~~~~~~~~~~~~~
puzzlebox.c:383:22: warning: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
                                        char           *p = strdupa(*(char **)optionsTable[o].arg),
                                                        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
puzzlebox.c:433:36: error: function definition is not allowed here
void            cuttext   (double s, char *t){
                                             ^
puzzlebox.c:448:27: error: function definition is not allowed here
int             box        (int part){
                                     ^
puzzlebox.c:1219:2: warning: implicit declaration of function 'box' is invalid in C99 [-Wimplicit-function-declaration]
        box(part);
        ^
4 warnings and 8 errors generated.
make: *** [puzzlebox] Error 1
Dora:PuzzleBox roy$

**Comment by revk** [comment]
I am not at all surprised - if you know how to get the gcc extensions working on a Mac that would be a great update.

**Comment by rkarlsba** [comment]
Which extension is that?

**Comment by revk** [comment]
Err - all the things that did not work for you... E.g. functions inside functions is a gcc special, and strdupa, and asprintf are extensions set with _GNU_SOURCE on a linux build.

Basically, no, it does not build on Mac.
And yes, if you know how to make such build on mac, that would be nice.
I gather it may be possible using homebrew, and some googling may help.

**Comment by rkarlsba** [comment]
Seems like the first issue I had, was that this has another version of indent, which messed up the source code rather than fix it, and then stumbled on those things you mentioned here. I guess I'll use a linux machine for this, then - worked well there.

**Comment by revk** [comment]
Ah, OK, indent did cause some of those, I see. I might remove that from make.

**Comment by Polaris34** [comment]
maybe it will help.
https://www.macports.org/
http://www.newthinktank.com/2013/08/how-to-install-gcc/

**Comment by rkarlsba** [comment]
Quick-and-dirty-fix (works)

- brew install gcc
- edit Makefile and change cc to /usr/local/opt/gcc/bin/gcc-8
- Add attached header file apple-strdupa.h
- Include it from puzzlebox.c

Build! :)
[apple-strdupa.h.txt](https://github.com/revk/PuzzleBox/files/2750005/apple-strdupa.h.txt)

**Comment by revk** [comment]
I may have to try that, thanks.

**Comment by rkarlsba** [comment]
The code for strdupa() was snipped from https://code.woboq.org/userspace/glibc/string/string.h.html

**Comment by rkarlsba** [comment]
Could you add the apple header to the source, please?

**Comment by revk** [comment]
Do make a pull request with any suggested changes. As long as they don't break linux builds, I'm happy to include them.
