### ISSUE TITLE
Text on the second and next sides is cropped

### ISSUE THREAD

**Issue by l1va** [revk/PuzzleBox#6]
Thanks for the project!
Found a problem with text. First side works good. I think picture shows the problem pretty clear.  

![image](https://user-images.githubusercontent.com/1406586/71166365-a004d780-2263-11ea-9df7-c2b4de7b4884.png)

**Comment by l1va** [comment]
found, that changing valign="center"  to valign="top" partially solve the problem (it moves the text to the bottom and do not crop).

**Comment by revk** [comment]
I have updated the code on the web site to fix this.
