### ISSUE TITLE
Brittle nubs

### ISSUE THREAD

**Issue by BenHorneIL** [revk/PuzzleBox#7]
I have noticed that when printing, that the nubs are quite brittle if the pieces are forced. Kids are not very gentle. I have printed another model and the nubs are stronger and dont break as much. Is there a way to increase the nub size/strength.

Here is a link to the model that i printed with re-inforced nubs:
https://www.thingiverse.com/thing:2607374

**Comment by Eddie-Hartman** [comment]
I second this. Had a few breaks with a few impatient relatives.

**Comment by revk** [comment]
Happy to take a pull request on this if you have ideas.
